p1_compile: 1_1.cpp
	g++ -Wall -o p1 1_1.cpp

p1_run: p1
	./p1

p2_compile: testStack.cpp
	g++ -Wall -o p2 testStack.cpp

p2_run: p2
	./p2

p3_compile: testLinkedList.cpp
	g++ -Wall -o p3 testLinkedList.cpp

p3_run: p3
	./p3
	
p4_compile: 1_4.cpp
	g++ -Wall -o p4 1_4.cpp

p4_run: p4
	./p4

p5_compile: 1_5.cpp
	g++ -Wall -o p5 1_5.cpp

p5_run: p5
	./p5