.PHONY: p1_a p1_b p1_c p1_d p2
p1_a: 8_1_a.py
	python3 8_1_a.py

p1_b: 8_1_b.py
	python3 8_1_b.py

p1_c: 8_1_c.py
	python3 8_1_c.py

p1_d: 8_1_d.py
	python3 8_1_d.py

p1_e: 8_1_e.py
	python3 8_1_e.py

p2: 8_2.py
	python3 8_2.py
	